'use client';
import { useEffect, useState } from 'react';

import { Sun, CloudSun, Wind, Droplets, Search, RefreshCw, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import './weather.css';
type Place={id:number;name:string;latitude:number;longitude:number;admin1?:string};

type Forecast={hourly:Record<string,(number|null)[]> & {time:number[]};timezone:string};
const paris:Place={id:2988507,name:'Paris',latitude:48.8534,longitude:2.3488,admin1:'Île-de-France'};
const fields=['temperature_2m','precipitation','wind_speed_10m','wind_gusts_10m','weather_code'];
const fmt=(n:number|null|undefined,d=0)=>n==null?'—':n.toLocaleString('fr-FR',{maximumFractionDigits:d});
const sky=(n:number|null)=>n==null?'Indisponible':n===0?'Ciel dégagé':n<=2?'Éclaircies':n===3?'Couvert':n<=48?'Brouillard':n<=57?'Bruine':n<=67?'Pluie':n<=77?'Neige':n<=82?'Averses':n<=86?'Averses de neige':'Orages';
async function getJson<T>(url:string,signal:AbortSignal){const r=await fetch(url,{signal:AbortSignal.any([signal,AbortSignal.timeout(15000)])});if(!r.ok)throw Error('Le service météo est momentanément indisponible. Réessayez.');return r.json() as Promise<T>;}
export default function Weather(){
 const [place,setPlace]=useState<Place>(paris),[query,setQuery]=useState(''),[matches,setMatches]=useState<Place[]>([]),[searchState,setSearchState]=useState(''),[data,setData]=useState<Forecast|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[day,setDay]=useState(''),[consulted,setConsulted]=useState(''),[now,setNow]=useState(0);
 useEffect(()=>{const c=new AbortController();if(query.trim().length<2)return()=>c.abort();const timer=setTimeout(async()=>{setSearchState('Recherche…');try{const p=new URLSearchParams({name:query.trim(),count:'10',language:'fr',format:'json',countryCode:'FR'});const r=await getJson<{results?:Place[]}>('https://geocoding-api.open-meteo.com/v1/search?'+p,c.signal);if(c.signal.aborted)return;const found=(r.results??[]).filter(p=>p.latitude>=41&&p.latitude<=51.5&&p.longitude>=-5.5&&p.longitude<=10);setMatches(found);setSearchState(found.length?'':'Aucune commune métropolitaine trouvée. Essayez un autre nom.');}catch{if(!c.signal.aborted)setSearchState('Recherche indisponible. Réessayez.');}},350);return()=>{clearTimeout(timer);c.abort();};},[query]);
 useEffect(()=>{const c=new AbortController();const p=new URLSearchParams({latitude:String(place.latitude),longitude:String(place.longitude),hourly:fields.join(','),models:'icon_eu',forecast_days:'5',timezone:'Europe/Paris',timeformat:'unixtime',wind_speed_unit:'kmh',temperature_unit:'celsius',precipitation_unit:'mm'});getJson<Forecast>('https://api.open-meteo.com/v1/dwd-icon?'+p,c.signal).then(r=>{if(c.signal.aborted)return;if(!r.hourly?.time?.length||fields.some(f=>!Array.isArray(r.hourly[f])))throw Error('Données de prévision incomplètes.');setData(r);setNow(Date.now());setConsulted(new Date().toLocaleString('fr-FR',{timeZone:'Europe/Paris'}));}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[place,refresh]);
 const date=(t:number)=>new Date(t*1000).toLocaleDateString('fr-CA',{timeZone:'Europe/Paris'});
 const indices=data?data.hourly.time.map((_,i)=>i).filter(i=>data.hourly.time[i]>=Math.floor(now/3600000)*3600&&fields.some(f=>data.hourly[f][i]!=null)):[];
 const days=[...new Set(indices.map(i=>date(data!.hourly.time[i])))];const active=days.includes(day)?day:days[0];const rows=indices.filter(i=>date(data!.hourly.time[i])===active);
 return <><header className="masthead"><a className="brand" href="https://alertes-meteo.com"><Sun/> alertes-météo<span>LE CLIMAT, AU QUOTIDIEN</span></a><a href="https://www.alertes-meteo.com/">Alertes-météo</a></header><main className="weather"><a className="back" href="https://www.alertes-meteo.com/"><ArrowLeft size={16}/> Retour à Alertes-météo</a><div className="weather-title"><div><p className="eyebrow">MODÈLE RÉGIONAL • EUROPE</p><h1>Prévisions plus fines (ICON-EU) <span>ICON EU 7 km</span></h1><p>Votre météo heure par heure, jusqu’à 5 jours.</p></div><div className="model-tag">ICON-EU <strong>≈ 7 km</strong></div></div>
 <section className="weather-panel"><label htmlFor="city-search">Rechercher une commune en France métropolitaine</label><div className="search"><Search size={20}/><Input id="city-search" placeholder="Paris, Lyon, Brest…" value={query} onChange={e=>{setQuery(e.target.value);setMatches([]);setSearchState('');}}/></div><output>{searchState}</output>{matches.length>0&&<ul className="city-results">{matches.filter(p=>p.latitude>=41&&p.latitude<=51.5&&p.longitude>=-5.5&&p.longitude<=10).map(p=><li key={p.id}><Button variant="ghost" onClick={()=>{setLoading(true);setData(null);setError('');setDay('');setPlace(p);setQuery('');setMatches([]);}}>{p.name}<span>{p.admin1}</span></Button></li>)}</ul>}
 <div className="forecast-heading"><div><h2>{place.name}</h2><p>{place.admin1} · {place.latitude.toFixed(3)}° N, {place.longitude.toFixed(3)}° E</p></div><Button variant="outline" disabled={loading} onClick={()=>{setLoading(true);setData(null);setError('');setRefresh(n=>n+1);}}><RefreshCw size={16}/> Actualiser</Button></div>
 {loading?<output className="weather-status">Chargement des prévisions ICON-EU…</output>:error?<div className="weather-status" role="alert"><p>{error}</p><Button onClick={()=>{setLoading(true);setData(null);setError('');setRefresh(n=>n+1);}}>Réessayer</Button></div>:data&&<><p className="weather-meta">Consulté le {consulted} · heures de Paris · prévisions modélisées</p><div className="forecast-days" aria-label="Choisir un jour">{days.map(d=><Button key={d} variant={active===d?'default':'outline'} aria-pressed={active===d} onClick={()=>setDay(d)}>{new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'})}</Button>)}</div>{rows.length? <Table><TableHeader><TableRow><TableHead>Heure</TableHead><TableHead>Temps</TableHead><TableHead><span><Sun size={16}/> Température</span></TableHead><TableHead><span><Droplets size={16}/> Précipitations</span></TableHead><TableHead><span><Wind size={16}/> Vent</span></TableHead><TableHead>Rafales</TableHead></TableRow></TableHeader><TableBody>{rows.map(i=><TableRow key={data.hourly.time[i]}><TableCell>{new Date(data.hourly.time[i]*1000).toLocaleTimeString('fr-FR',{timeZone:'Europe/Paris',hour:'2-digit',minute:'2-digit'})}</TableCell><TableCell>{sky(data.hourly.weather_code[i])}</TableCell><TableCell className="temperature">{fmt(data.hourly.temperature_2m[i],1)} °C</TableCell><TableCell>{fmt(data.hourly.precipitation[i],1)} mm</TableCell><TableCell>{fmt(data.hourly.wind_speed_10m[i])} km/h</TableCell><TableCell>{fmt(data.hourly.wind_gusts_10m[i])} km/h</TableCell></TableRow>)}</TableBody></Table>:<p>Aucune échéance disponible pour cette localisation.</p>}</>}
 </section><section className="weather-notes"><CloudSun/><div><h2>Une maille plus fine, avec ses limites</h2><p>ICON-EU, modèle du service météorologique allemand DWD, couvre l’Europe avec une maille d’environ 7 km. Les valeurs horaires au-delà de 78 heures sont interpolées à partir de pas de 3 heures. Une maille fine ne garantit pas la précision à l’échelle d’une rue, notamment en montagne et lors des orages.</p><p>Température à 2 m ; vent et rafales à 10 m. Les précipitations incluent pluie et neige en équivalent eau, cumulées sur l’heure précédente. « — » indique une donnée manquante. L’heure de consultation n’est pas l’heure du calcul du modèle.</p><p>Source : <a href="https://open-meteo.com/en/docs/dwd-api" target="_blank" rel="noreferrer">DWD via Open-Meteo</a> · <a href="https://open-meteo.com/en/terms" target="_blank" rel="noreferrer">Conditions d’utilisation</a>. API gratuite pour usage non commercial ; une offre adaptée est nécessaire pour une exploitation commerciale.</p></div></section></main></>;
}





