'use client';
import { useEffect, useState } from 'react';
import { searchPlaces, getForecast, type Place, type Forecast } from '@/lib/icon-data';

import { Sun, CloudSun, Wind, Droplets, Search, RefreshCw, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import './weather.css';



const paris:Place={id:'75056',department:'75',name:'Paris',latitude:48.8534,longitude:2.3488,admin1:'Île-de-France'};
const fields=['temperature_2m','precipitation','wind_speed_10m','wind_gusts_10m','cloud_cover'];
const fmt=(n:number|null|undefined,d=0)=>n==null?'—':n.toLocaleString('fr-FR',{maximumFractionDigits:d});
export default function Weather(){
 const [place,setPlace]=useState<Place>(paris),[query,setQuery]=useState(''),[matches,setMatches]=useState<Place[]>([]),[searchState,setSearchState]=useState(''),[data,setData]=useState<Forecast|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[day,setDay]=useState(''),[consulted,setConsulted]=useState(''),[now,setNow]=useState(0);
 useEffect(()=>{const c=new AbortController();if(query.trim().length<2)return()=>c.abort();const timer=setTimeout(async()=>{setSearchState('Recherche…');try{const found=await searchPlaces(query,c.signal);if(c.signal.aborted)return;setMatches(found);setSearchState(found.length?'':'Aucune commune métropolitaine trouvée. Essayez un autre nom.');}catch{if(!c.signal.aborted)setSearchState('Recherche indisponible. Réessayez.');}},350);return()=>{clearTimeout(timer);c.abort();};},[query]);
 useEffect(()=>{const c=new AbortController();getForecast(place,c.signal).then(r=>{if(c.signal.aborted)return;if(!r.hourly?.time?.length||fields.some(f=>!Array.isArray(r.hourly[f])))throw Error('Données de prévision incomplètes.');setData(r);setNow(Date.now());setConsulted(new Date().toLocaleString('fr-FR',{timeZone:'Europe/Paris'}));}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[place,refresh]);
 const date=(t:number)=>new Date(t*1000).toLocaleDateString('fr-CA',{timeZone:'Europe/Paris'});
 const indices=data?data.hourly.time.map((_,i)=>i).filter(i=>data.hourly.time[i]>=Math.floor(now/3600000)*3600&&fields.some(f=>data.hourly[f][i]!=null)):[];
 const days=[...new Set(indices.map(i=>date(data!.hourly.time[i])))];const active=days.includes(day)?day:days[0];const rows=indices.filter(i=>date(data!.hourly.time[i])===active);
 return <><header className="masthead"><a className="brand" href="https://alertes-meteo.com"><Sun/> alertes-météo<span>LE CLIMAT, AU QUOTIDIEN</span></a><a href="https://www.alertes-meteo.com/">Alertes-météo</a></header><main className="weather"><a className="back" href="https://www.alertes-meteo.com/"><ArrowLeft size={16}/> Retour à Alertes-météo</a><div className="weather-title"><div><p className="eyebrow">MODÈLE RÉGIONAL • EUROPE</p><h1>Prévisions plus fines (ICON-EU) <span>ICON EU 7 km</span></h1><p>Votre météo heure par heure, jusqu’à 5 jours.</p></div><div className="model-tag">ICON-EU <strong>≈ 7 km</strong></div></div>
 <section className="weather-panel"><label htmlFor="city-search">Rechercher une commune en France métropolitaine</label><div className="search"><Search size={20}/><Input id="city-search" placeholder="Paris, Lyon, Brest…" value={query} onChange={e=>{setQuery(e.target.value);setMatches([]);setSearchState('');}}/></div><output>{searchState}</output>{matches.length>0&&<ul className="city-results">{matches.filter(p=>p.latitude>=41&&p.latitude<=51.5&&p.longitude>=-5.5&&p.longitude<=10).map(p=><li key={p.id}><Button variant="ghost" onClick={()=>{setLoading(true);setData(null);setError('');setDay('');setPlace(p);setQuery('');setMatches([]);}}>{p.name}<span>{p.admin1}</span></Button></li>)}</ul>}
 <div className="forecast-heading"><div><h2>{place.name}</h2><p>{place.admin1} · {place.latitude.toFixed(3)}° N, {place.longitude.toFixed(3)}° E</p></div><Button variant="outline" disabled={loading} onClick={()=>{setLoading(true);setData(null);setError('');setRefresh(n=>n+1);}}><RefreshCw size={16}/> Actualiser</Button></div>
 {loading?<output className="weather-status">Chargement des prévisions ICON-EU…</output>:error?<div className="weather-status" role="alert"><p>{error}</p><Button onClick={()=>{setLoading(true);setData(null);setError('');setRefresh(n=>n+1);}}>Réessayer</Button></div>:data&&<><p className="weather-meta">Calcul du {new Date(data.model_run).toLocaleString("fr-FR",{timeZone:"Europe/Paris"})} · consulté le {consulted} · heures de Paris</p><div className="forecast-days" aria-label="Choisir un jour">{days.map(d=><Button key={d} variant={active===d?'default':'outline'} aria-pressed={active===d} onClick={()=>setDay(d)}>{new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'})}</Button>)}</div>{rows.length? <Table><TableHeader><TableRow><TableHead>Heure</TableHead><TableHead>Nuages</TableHead><TableHead><span><Sun size={16}/> Température</span></TableHead><TableHead><span><Droplets size={16}/> Précipitations</span></TableHead><TableHead><span><Wind size={16}/> Vent</span></TableHead><TableHead>Rafales</TableHead></TableRow></TableHeader><TableBody>{rows.map(i=><TableRow key={data.hourly.time[i]}><TableCell>{new Date(data.hourly.time[i]*1000).toLocaleTimeString('fr-FR',{timeZone:'Europe/Paris',hour:'2-digit',minute:'2-digit'})}</TableCell><TableCell>{fmt(data.hourly.cloud_cover[i])} %</TableCell><TableCell className="temperature">{fmt(data.hourly.temperature_2m[i],1)} °C</TableCell><TableCell>{fmt(data.hourly.precipitation[i],1)} mm</TableCell><TableCell>{fmt(data.hourly.wind_speed_10m[i])} km/h</TableCell><TableCell>{fmt(data.hourly.wind_gusts_10m[i])} km/h / {data.gust_period_hours[i]} h</TableCell></TableRow>)}</TableBody></Table>:<p>Prévisions expirées ou indisponibles. Vérifiez le dernier run GitHub.</p>}</>}
 </section><section className="weather-notes"><CloudSun/><div><h2>Une maille plus fine, avec ses limites</h2><p>ICON-EU, modèle du service météorologique allemand DWD, couvre l’Europe avec une maille d’environ 7 km. Après +78 h, température, vent et nuages sont interpolés ; la pluie est répartie sur trois heures. Les rafales gardent leur période native, indiquée dans le tableau. Une maille fine ne garantit pas la précision à l’échelle d’une rue, notamment en montagne et lors des orages.</p><p>Point de grille le plus proche de la commune, sans correction locale d’altitude. Température à 2 m ; vent et rafales à 10 m. Les précipitations incluent pluie et neige en équivalent eau, cumulées sur l’heure précédente. « — » indique une donnée manquante. L’heure de consultation n’est pas l’heure du calcul du modèle.</p><p>Source : <a href="https://opendata.dwd.de/weather/nwp/icon-eu/" target="_blank" rel="noreferrer">DWD Open Data</a>. Prévisions préparées automatiquement par <a href="https://github.com/alertesmeteo-hub/ICON-EU-7-km/actions/workflows/update-icon-eu.yml" target="_blank" rel="noreferrer">GitHub Actions</a>.</p></div></section></main></>;
}






